wandb_version: 1

dataset:
  desc: null
  value: Chengdu_Taxi_Sample1_10_u50
read_pkl:
  desc: null
  value: false
times:
  desc: null
  value: 1
epochs:
  desc: null
  value: 400
train_batch:
  desc: null
  value: 8
valid_batch:
  desc: null
  value: 8
test_batch:
  desc: null
  value: 8
patience:
  desc: null
  value: 20
grid_size:
  desc: null
  value: 40
gcn_lr:
  desc: null
  value: 0.01
weight_decay:
  desc: null
  value: 0.0005
localGcn_hidden:
  desc: null
  value: 512
globalGcn_hidden:
  desc: null
  value: 512
gcn_dropout:
  desc: null
  value: 0.5
Attn_Strategy:
  desc: null
  value: cos
Softmax_Strategy:
  desc: null
  value: complex
Pool_Strategy:
  desc: null
  value: max
merge_use:
  desc: null
  value: true
state_use:
  desc: null
  value: true
time_use:
  desc: null
  value: true
d_model:
  desc: null
  value: 128
encode_lr:
  desc: null
  value: 0.001
d_k:
  desc: null
  value: 64
d_v:
  desc: null
  value: 64
d_ff:
  desc: null
  value: 512
n_heads:
  desc: null
  value: 5
n_layers:
  desc: null
  value: 2
exp_id:
  desc: null
  value: '2310280041'
seed:
  desc: null
  value: 0
gpu_id:
  desc: null
  value: 0
attack:
  desc: null
  value: Trigger
user_rate:
  desc: null
  value: 0.05
testset_attack_ratio:
  desc: null
  value: 0.5
attack_label:
  desc: null
  value: Single
malicious_label:
  desc: null
  value: 1
domain:
  desc: null
  value: ST
attack_position:
  desc: null
  value: 0.5
attack_ratio:
  desc: null
  value: 0.25
malicious_label_ratio:
  desc: null
  value: 0.5
meanS:
  desc: null
  value: 0.0
stddevS:
  desc: null
  value: 0.005
meanT:
  desc: null
  value: 0.0
stddevT:
  desc: null
  value: 0.05
deltaS:
  desc: null
  value: 0.002
directionS:
  desc: null
  value: 0
deltaT:
  desc: null
  value: 30.0
stretch_length:
  desc: null
  value: 30.0
trigger_shape:
  desc: null
  value: 2Triangle
trigger_position:
  desc: null
  value: 0.5
trigger_size:
  desc: null
  value: 5.0
wandb:
  desc: null
  value: true
PROJECT_NAME:
  desc: null
  value: TBA-TUL
attack_parameter:
  desc: null
  value:
    meanS: 0.0
    stddevS: 0.005
    meanT: 0.0
    stddevT: 0.05
    deltaS: 0.002
    directionS: 0
    deltaT: 30.0
    stretch_length: 30.0
ckpt_path:
  desc: null
  value: ./checkpoint/tul/2310280041/
atk_path:
  desc: null
  value: ./cache/tul/2310280041/atk/
device:
  desc: null
  value: cuda:0
original_data_path:
  desc: null
  value: ./data/tul/chengdu/raw/Chengdu_Taxi_Sample1_10_u50.dyna
malicious_user_set:
  desc: null
  value:
  - 43
  - 45
_wandb:
  desc: null
  value:
    code_path: code/base_models/trajecotory_user_linking/main.py
    python_version: 3.7.16
    cli_version: 0.15.12
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1698513966.807844
    t:
      1:
      - 1
      - 5
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 51
      - 53
      - 55
      3:
      - 2
      - 13
      - 15
      - 16
      - 23
      4: 3.7.16
      5: 0.15.12
      8:
      - 5
      13: linux-x86_64
